# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Job.create( user_id: "3", title:"Toilet leaking", location:"Cherry Hill", cost: "100", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Plumbing")

Job.create( user_id: "5", title:"Looking for tutor", location:"Glassboro", cost: "50", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Other")

Job.create( user_id: "4", title:"Sink is clogged", location:"Deptford", cost: "150", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Plumbing")

Job.create( user_id: "7", title:"Computer has virus", location:"Philadelphia", cost: "80", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"I.T.") 

Job.create( user_id: "8", title:"Need Babysitter fast!", location:"Marlton", cost: "75", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Babysitter") 

Job.create( user_id: "1", title:"Babysitter needed", location:"Pitman", cost: "55", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Babysitter") 

Job.create( user_id: "2", title:"Mural painting", location:"Moorestown", cost: "1000", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Design/Art") 

Job.create( user_id: "3", title:"Chop down my tree!", location:"Franklinville", cost: "200", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Yard Work") 

Job.create( user_id: "10", title:"Need new fuse box", location:"Camden", cost: "400", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Electrical") 

Job.create( user_id: "9", title:"Front steps repair", location:"Clayton", cost: "100", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Carpentry") 

Job.create( user_id: "6", title:"Moving need help !", location:"Deptford", cost: "100", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Moving") 

Job.create( user_id: "4", title:"Portrait of mom", location:"Cherry Hill", cost: "350", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Design/Art") 

Job.create( user_id: "2", title:"Oil change", location:"New Egypt", cost: "60", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Automotive") 

Job.create( user_id: "7", title:"Flat tire", location:"Philadelphia", cost: "100", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Automotive") 

Job.create( user_id: "1", title:"Emergency! Babysitter now", location:"Pitman", cost: "100", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Babysitter") 

Job.create( user_id: "4", title:"Weekly shopper, negotiable", location:"Medford", cost: "35", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur sem commodo lacus lacinia placerat. Cras accumsan ornare est ut accumsan. Etiam erat lectus, venenatis eget nulla nec, dictum pellentesque ligula. Phasellus sodales et tortor sit amet laoreet. Etiam molestie urna non tortor vehicula, nec commodo libero tempor. Nulla tempus quis ex quis rutrum. Aliquam tristique tortor vitae blandit scelerisque. Fusce hendrerit auctor ante vel rutrum. Suspendisse porta efficitur vehicula.

Ut pharetra, leo sit amet viverra rutrum, urna massa vulputate dui, at aliquet quam urna sit amet mi. Cras accumsan a felis in varius. Sed metus ligula, placerat eu venenatis ut, feugiat in ante. Mauris pretium ante sit amet quam auctor bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras pharetra, elit vitae fringilla feugiat, mi nibh tempus tortor, ac sodales quam sapien ac eros. Duis fringilla tortor ex, ac pellentesque risus pellentesque ac. Vivamus semper consectetur eros tristique pharetra.", category:"Personal Shopper")
